/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}"
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#dae2fd",
        "on-secondary": "#ffffff",
        "primary-fixed": "#ffdbca",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        surface: "#fbf9f5",
        "inverse-surface": "#30312e",
        "on-secondary-fixed": "#131b2e",
        secondary: "#565e74",
        "surface-container-highest": "#e4e2de",
        "inverse-on-surface": "#f2f0ed",
        outline: "#8c7164",
        "on-primary-container": "#582200",
        "on-primary": "#ffffff",
        "surface-dim": "#dbdad6",
        "inverse-primary": "#ffb690",
        "secondary-fixed-dim": "#bec6e0",
        "on-tertiary-fixed-variant": "#5b4220",
        "on-tertiary-fixed": "#2a1800",
        "outline-variant": "#e0c0b1",
        "error-container": "#ffdad6",
        "primary-container": "#f97316",
        "on-secondary-container": "#5c647a",
        "on-secondary-fixed-variant": "#3f465c",
        background: "#fbf9f5",
        primary: "#9d4300",
        "on-surface": "#1b1c1a",
        "surface-container-low": "#f5f3ef",
        "surface-container-high": "#eae8e4",
        error: "#ba1a1a",
        "on-surface-variant": "#584237",
        "surface-variant": "#e4e2de",
        "tertiary-fixed-dim": "#e6c095",
        tertiary: "#755935",
        "on-background": "#1b1c1a",
        "secondary-container": "#dae2fd",
        "tertiary-container": "#b7956c",
        "on-primary-fixed": "#341100",
        "surface-tint": "#9d4300",
        "tertiary-fixed": "#ffddb7",
        "primary-fixed-dim": "#ffb690",
        "on-tertiary-container": "#452e0e",
        "surface-container": "#efeeea",
        "surface-bright": "#fbf9f5",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#783200",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-xl": "3rem",
        "space-md": "1rem",
        "gutter-mobile": "1rem",
        "space-sm": "0.5rem",
        margin: "2rem",
        "space-lg": "1.75rem",
        gutter: "1.5rem",
      },
      fontFamily: {
        "headline-sm": ["Plus Jakarta Sans"],
        "label-badge": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "label-code": ["JetBrains Mono"],
        "display-hero": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "display-hero-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "headline-sm": [
          "18px",
          { lineHeight: "24px", fontWeight: "600" },
        ],
        "label-badge": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.04em",
            fontWeight: "600",
          },
        ],
        "headline-md": [
          "22px",
          {
            lineHeight: "28px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "label-code": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.02em",
            fontWeight: "500",
          },
        ],
        "display-hero": [
          "56px",
          {
            lineHeight: "64px",
            letterSpacing: "-0.03em",
            fontWeight: "800",
          },
        ],
        "headline-lg-mobile": [
          "26px",
          {
            lineHeight: "34px",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "display-hero-mobile": [
          "36px",
          {
            lineHeight: "44px",
            letterSpacing: "-0.02em",
            fontWeight: "800",
          },
        ],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}