/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}"
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "var(--secondary-fixed)",
        "on-secondary": "var(--on-secondary)",
        "primary-fixed": "var(--primary-fixed)",
        "on-tertiary": "var(--on-tertiary)",
        "on-error-container": "var(--on-error-container)",
        surface: "var(--surface)",
        "inverse-surface": "var(--inverse-surface)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        secondary: "var(--secondary)",
        "surface-container-highest": "var(--surface-container-highest)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        outline: "var(--outline)",
        "on-primary-container": "var(--on-primary-container)",
        "on-primary": "var(--on-primary)",
        "surface-dim": "var(--surface-dim)",
        "inverse-primary": "var(--inverse-primary)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "outline-variant": "var(--outline-variant)",
        "error-container": "var(--error-container)",
        "primary-container": "var(--primary-container)",
        "on-secondary-container": "var(--on-secondary-container)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        background: "var(--background)",
        primary: "var(--primary)",
        "on-surface": "var(--on-surface)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-container-high": "var(--surface-container-high)",
        error: "var(--error)",
        "on-surface-variant": "var(--on-surface-variant)",
        "surface-variant": "var(--surface-variant)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        tertiary: "var(--tertiary)",
        "on-background": "var(--on-background)",
        "secondary-container": "var(--secondary-container)",
        "tertiary-container": "var(--tertiary-container)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "surface-tint": "var(--surface-tint)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "surface-container": "var(--surface-container)",
        "surface-bright": "var(--surface-bright)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "on-error": "var(--on-error)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-xl": "3rem",
        "space-md": "1rem",
        "gutter-mobile": "1rem",
        "space-sm": "0.5rem",
        margin: "2rem",
        "space-lg": "1.75rem",
        gutter: "1.5rem",
      },
      fontFamily: {
        "headline-sm": ["Plus Jakarta Sans"],
        "label-badge": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "label-code": ["JetBrains Mono"],
        "display-hero": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "display-hero-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "headline-sm": [
          "18px",
          { lineHeight: "24px", fontWeight: "600" },
        ],
        "label-badge": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.04em",
            fontWeight: "600",
          },
        ],
        "headline-md": [
          "22px",
          {
            lineHeight: "28px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "label-code": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.02em",
            fontWeight: "500",
          },
        ],
        "display-hero": [
          "56px",
          {
            lineHeight: "64px",
            letterSpacing: "-0.03em",
            fontWeight: "800",
          },
        ],
        "headline-lg-mobile": [
          "26px",
          {
            lineHeight: "34px",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "display-hero-mobile": [
          "36px",
          {
            lineHeight: "44px",
            letterSpacing: "-0.02em",
            fontWeight: "800",
          },
        ],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}